name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/ROHANPATAKAR/personal-portfolio/blob/main/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/ROHANPATAKAR/personal-portfolio"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "ROHAN PATANKAR"
  homepage = "https://www.linkedin.com/in/rohanpatankar926/"
